### ISSUE TITLE
failure to link ospStudio

### ISSUE THREAD

**Issue by jfavre** [ospray/ospray_studio#1]
Dear developers

I am compiling the ospray_studio on an Ubuntu (18.04.1 LTS) laptop (g++ v7.3.0) but fail to link. Here are the error I see:

cd /local/apps/ospray_studio/build/app && /local/apps/cmake-3.12.2-Linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/ospStudio.dir/link.txt --verbose=1
/usr/bin/c++    -rdynamic CMakeFiles/ospStudio.dir/ospStudioMain.cpp.o  -o ../ospStudio -Wl,-rpath,/local/apps/ospray_studio/build:/local/apps/ospray-1.7.2.x86_64.linux/lib: ../libospray_studio.so.1.7.2 /local/apps/ospray-1.7.2.x86_64.linux/lib/libospray_sg.so -pthread ../libospray_imgui.so.1.7.2 -lOpenGL -lGLX -lGLU ../libospray_tfn.so.1.7.2 /local/apps/ospray-1.7.2.x86_64.linux/lib/libtbb.so /local/apps/ospray-1.7.2.x86_64.linux/lib/libtbb.so.2 /local/apps/ospray-1.7.2.x86_64.linux/lib/libtbbmalloc.so /local/apps/ospray-1.7.2.x86_64.linux/lib/libtbbmalloc.so.2 /local/apps/ospray-1.7.2.x86_64.linux/lib/libembree.so /local/apps/ospray-1.7.2.x86_64.linux/lib/libembree3.so.3 /local/apps/ospray-1.7.2.x86_64.linux/lib/libospray.so /local/apps/ospray-1.7.2.x86_64.linux/lib/libospray_module_ispc.so /local/apps/ospray-1.7.2.x86_64.linux/lib/libospray_common.so /usr/lib/x86_64-linux-gnu/libglfw.so.3.2 
CMakeFiles/ospStudio.dir/ospStudioMain.cpp.o: In function `parseCommandLineSG(int, char const**&, ospray::sg::Frame&)':
ospStudioMain.cpp:(.text+0xdc1): undefined reference to `ospray::sg::Node::childrenRecursive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
ospStudioMain.cpp:(.text+0xe12): undefined reference to `ospray::sg::Node::childRecursive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
ospStudioMain.cpp:(.text+0xff6): undefined reference to `ospray::sg::Node::createChild(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ospcommon::utility::Any, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
ospStudioMain.cpp:(.text+0x17ea): undefined reference to `ospray::sg::Node::name[abi:cxx11]() const'
CMakeFiles/ospStudio.dir/ospStudioMain.cpp.o: In function `importFilesFromCommandLine(ospray::sg::Frame const&)':
ospStudioMain.cpp:(.text+0x197c): undefined reference to `ospray::sg::Node::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'

any help would be appreciated. TIA

**Comment by jeffamstutz** [comment]
Howdy,

Did you use the same compiler to compile OSPRay? It looks like ```std::string``` ABI related.

Regardless, I'll have a look in a local build in the same OS environment to see if I can reproduce this myself.

**Comment by jeffamstutz** [comment]
I'm planning on finding an exact fix by the end of the day, but for the time being I think you can just compile OSPRay and OSPRay Studio with the same compiler and it should be fine. However, I was able to reproduce this using the pre-built OSPRay binaries....I just want to see how these ABI link issues play out before choosing a solution to generally recommend.

**Comment by jeffamstutz** [comment]
It looks like this ABI issue can't be resolved between the old ```libstdc++.so``` we build the OSPRay binaries with and the new one found by default on Ubuntu 18.04. The above remedy of compiling everything yourself will work just fine, and appears to be the only option at the moment.

I'll be on the lookout for better ways to deal with C++ ABI issues in the future. Currently the problem lies in the fact that OSPRay Studio currently uses classes underneath the OSPRay API (```libospcommon.so```, specifically). Those will not remain in OSPRay itself forever, so there's a chance that OSPRay Studio will only rely on the OSPRay API itself in the future, which is easier to maintain ABI compatibility with.

**Comment by jfavre** [comment]
+1
./ospStudio running fine. Thanks.
