### ISSUE TITLE
exr support ?

### ISSUE THREAD

**Issue by nyue** [ospray/ospray_studio#11]
I am testing out the build of ospray studio 0.10.0 on Windows.

I render out the test scene NewSponza with the following command line options

```
ospray_studio-0.10.0-win64\bin\ospStudio.exe batch --renderer pathtracer NewSponza_Main_Blender_glTF.gltf --image nyue2 --camera 1 --format exr
```

I get an error about EXR not being supported

```
#importGLTF(W): mismatching COLOR_0 size
#importGLTF(I): finished import!
Loading camera from index: 1
frame 1 variance inf
No exporter found for type exr
...finished!
```

I wanted to try out OpenEXR to get better dynamic range of the output colors

**Comment by isharma25** [comment]
Please build with cmake flag `ENABLE_EXR` enabled and check if `OPENEXR_ROOT` is set correctly.

**Comment by BruceCherniak** [comment]
To limit release size and compatibility issues, the binaries we release to github do not have OpenImageIO or OpenEXR enabled.  Those are optional dependencies.  https://github.com/ospray/ospray_studio#optional-dependencies.

Without rebuilding, you should be able to export to the `hdr` format.

**Comment by nyue** [comment]
OK. I will test HDR image format.

I am trying to match the quality of the images that came with the NewSponza examples, any suggestions regarding flags and settings I can use ?

**Comment by BruceCherniak** [comment]
I believe those reference images are the Arnold renderer images.  You should be able to come pretty close with OSPRay Studio and the `kloppenheim_05_4k.hdr` HDRI that is in the textures folder.  You'll need to set the HDRI direction to (1.0, 0.0, 0.33) to get about the same lighting position.  Then, set the light intensity to 4.0.  Each of the Arnold renders have different exposure settings, so you'll need to play with the Studio tone-mapper settings to get closer to these images.

The pre-defined cameras in the `camera` menu will get you to the shot location -- however, be careful, you move the camera while using one of these settings you'll overwrite the setting until the next time you load the scene.

I'll post all of this on the Studio website when I get a chance, but this version of Sponza was just released yesterday. ;-)

**Comment by BruceCherniak** [comment]
I’ll go ahead and close this, as the original issue is resolved. Please follow up on any Sponza scene questions via email. Thanks.
