### ISSUE TITLE
OpenImageIO and OpenEXR version recommendations ?

### ISSUE THREAD

**Issue by nyue** [ospray/ospray_studio#13]
It would be helpful to indicate which version of OpenImageIO and OpenEXR has been used successfully with OSPray Studio to save us from version combinatorial explosion to try out when build fails or we encounter problems.

Thank you.

**Comment by BruceCherniak** [comment]
Hi.  Thanks, that's a good idea.  I'll add that to the build documentation.  For me, on Ubuntu, I've just been using the package installed versions of both.  I believe OIIO-dev 2.1.12 and OpenEXR-dev 2.3.2.

**Comment by nyue** [comment]
Got it.
