### ISSUE TITLE
OspRay Studio import Medical raw data，why will it failure and force exit? 

### ISSUE THREAD

**Issue by ChenZhiMing66** [ospray/ospray_studio#20]
![微信图片_20221014112732](https://user-images.githubusercontent.com/55489611/195755624-d4048426-92e2-4ac8-a28d-ac54c992ba59.png)

**Comment by johguenther** [comment]
For raw volumes Studio needs to know the metadata (at least dimensions and voxel type) of the volume, which you can (currently only) pass on the command line:
```sh
ospStudio --dimensions 256 256 256  --voxelType 2500  skull_256x256x256_uint8.raw
```

For more options and explanations see
```sh
ospStudio --help
```

**Comment by ChenZhiMing66** [comment]
It still has the same problem. Should I input more commands?
![image](https://user-images.githubusercontent.com/55489611/195841541-94cd1762-834d-41be-bdc5-6af7ca089cfa.png)

**Comment by supertidiot** [comment]
> For raw volumes Studio needs to know the metadata (at least dimensions and voxel type) of the volume, which you can (currently only) pass on the command line:
> 
> ```shell
> ospStudio --dimensions 256 256 256  --voxelType 2500  skull_256x256x256_uint8.raw
> ```
> 
> For more options and explanations see
> 
> ```shell
> ospStudio --help
> ```

**Comment by BruceCherniak** [comment]
Hi, does closing this mean that you were able to get it working?  If not, I'm happy to help resolve it further.  raw volumes can be tricky.

**Comment by ChenZhiMing66** [comment]
> Hi, does closing this mean that you were able to get it working? If not, I'm happy to help resolve it further. raw volumes can be tricky.

Hi, I haven't got it working yet. So what should I do to solve this problem?

**Comment by BruceCherniak** [comment]
From your comment above `It still has the same problem.`:
https://user-images.githubusercontent.com/55489611/195841541-94cd1762-834d-41be-bdc5-6af7ca089cfa.png

Appears you are trying to load this as `FLOAT` data by setting `--voxelType 6000`.  Use `--voxelType 2500`, as Johannes as suggested above.\

The enum types are here https://github.com/ospray/ospray/blob/fdda0889f9143a8b20f26389c22d1691f1a6a527/ospray/include/ospray/OSPEnums.h#L80

**Comment by ChenZhiMing66** [comment]
> From your comment above `It still has the same problem.`: https://user-images.githubusercontent.com/55489611/195841541-94cd1762-834d-41be-bdc5-6af7ca089cfa.png
> 
> Appears you are trying to load this as `FLOAT` data by setting `--voxelType 6000`. Use `--voxelType 2500`, as Johannes as suggested above.\
> 
> The enum types are here https://github.com/ospray/ospray/blob/fdda0889f9143a8b20f26389c22d1691f1a6a527/ospray/include/ospray/OSPEnums.h#L80

![ospray](https://user-images.githubusercontent.com/55489611/196089689-f9ef20a8-0abb-4171-99c7-a38f18795184.jpg)
But I have tried  `--voxelType 2500`  and it still doesn't work.

**Comment by BruceCherniak** [comment]
I see. Hmm.  Is `skull_256x256x256_uint8.raw` something you can share with us?  I will try it locally.

**Comment by johguenther** [comment]
It is OS specific: works on Linux, but I can reproduce the exception on Windows.

**Comment by ChenZhiMing66** [comment]
> I see. Hmm. Is `skull_256x256x256_uint8.raw` something you can share with us? I will try it locally.

Sure. I have upload in my git. Or Could I ask your email ? And I will send it to you.

**Comment by ChenZhiMing66** [comment]
> It is OS specific: works on Linux, but I can reproduce the exception on Windows.

Yes. I run it on Windows. So can it import this type of data on Windows?  And I see that it says `Loading volumes with default volume parameters` . Does it mean that the command parameters I inputed do not work?

**Comment by johguenther** [comment]
We found the problem, the fix is in the `devel` branch.

**Comment by ChenZhiMing66** [comment]
Thank you!! I was finally able to test the devel version and it solves the bug perfectly.
