### ISSUE TITLE
The --denoiser option is ineffective in GUI mode

### ISSUE THREAD

**Issue by howetuft** [ospray/ospray_studio#21]
Hello,

As stated in the title: if you pass --denoiser in the command line and if you are in GUI mode, no denoising is processed.

I think it's because the `floatFormat` of the frame buffer is not automatically set to `true`, unlike in batch mode (https://github.com/ospray/ospray_studio/blob/master/app/Batch.cpp#L322).

--> Could you please have a look and fix it? Many thanks in advance!

By the way, nice-to-have: it would also be convenient to be able from the command line to control whether the denoising is applied for each frame or on final  frame only...

**Comment by BruceCherniak** [comment]
Hello,

Good point.  There are definitely some inconsistencies between GUI and batch modes that should be resolved.  These were developed as separate workflows, but need to be somewhat merged back together.  I'll file an internal issue to work on these.

Thanks

**Comment by howetuft** [comment]
Hello Bruce,
By the way, happy new year 2023 to you and all Ospray Studio team! 
H.

**Comment by BruceCherniak** [comment]
Hi.  When you get a chance, all of the features we talked about should be fixed and working on the devel branch.  If so, we can close this issue?  Thanks.

**Comment by howetuft** [comment]
Yes we can! Thank you very much for the fixes, I close the issue immediately.
