### ISSUE TITLE
Loaded OBJ does not show up ?

### ISSUE THREAD

**Issue by nyue** [ospray/ospray_studio#3]
Hi,

  I loaded an obj (exported from blender3d) [the monkey.obj], it does not show up in the ospray_studio window.

  What am I doing wrong ?

Cheers

**Comment by BruceCherniak** [comment]
Impossible to say without more information.  Are you able to display the simple demo scenes?  `file -> Demo scene -> tutorial_scene` ?

**Comment by BruceCherniak** [comment]
This will likely be a duplicate of issue #2 that we're discussing.

**Comment by BruceCherniak** [comment]
Having talked more in issue #2, this is definitely a duplicate of that.  Closing.
