### ISSUE TITLE
What happened to the web pages - https://www.ospray.org/ospray_studio/

### ISSUE THREAD

**Issue by davidpwayne** [ospray/ospray_studio#31]
This site had some very good still images and panoramas of the Bentley car show room.  The metallic materials used on the cars are superior to what Cadalog can render in our new SketchUp plug-in called PodiumxRT.  I would really like access to those images and panoramas.

**Comment by johguenther** [comment]
Sorry, that was a glitch when we migrated repositories. Studio's website is available again.

**Comment by davidpwayne** [comment]
Thank you
