### ISSUE TITLE
Adding sphere spoils renderbuffer

### ISSUE THREAD

**Issue by iqch** [ospray/ospray_studio#4]
Windows version, Win10, from zip archive
just add demo scenes 
### WITH SPHERE
![2021-09-14_23-01-08](https://user-images.githubusercontent.com/2112777/133325834-6f65cb6c-c0d2-4b90-850e-470c04fc761d.png)
### WITHOUT (INVISIBLE)
![2021-09-14_23-00-27](https://user-images.githubusercontent.com/2112777/133325886-cb3599d9-d248-4beb-904b-063295909b85.png)
### LATER...
![2021-09-14_23-09-29](https://user-images.githubusercontent.com/2112777/133326816-92161c2c-3995-4acb-913f-e7ad2457ef64.png)

**Comment by BruceCherniak** [comment]
Hmm.  So, you just started with the Demo Scene `particle_volume` and then added the `sphere` and toggled the sphere's visibility?

I will try to reproduce this on the Windows binaries.

There is a bug in the release binaries where the sphere's material is invalid, but I don't think it would have this affect.  That has been fixed and will be in the next release.

**Comment by BruceCherniak** [comment]
I revise my earlier comment.  That invalid material may look black but it's insidious and causes the artifacts you're observing.  Within the next week, we'll be releasing a bugfix release that contains a couple of fixes -- this included.  Thanks for the report.

**Comment by BruceCherniak** [comment]
The v0.8.1 bug fix release that I just completed fixes this invalid material.  This should resolve the problems you were seeing.

**Comment by BruceCherniak** [comment]
Please reopen if you still see this behavior.
