### ISSUE TITLE
Metallic principled shader renders black

### ISSUE THREAD

**Issue by howetuft** [ospray/ospray_studio#5]
This [Project](https://github.com/ospray/ospray_studio/files/7271412/Project.zip) is expected to render a golden cube. Unfortunately, instead, the cube is dark:
![studio 0000](https://user-images.githubusercontent.com/34142192/135715777-533b651f-b398-46ad-9725-b6c178b7d129.png)
I'm using the Principled shader with `metallic 1.0`, I suspect a problem with it but I can't figure out what's wrong: can someone help me please? Many thanks in advance...

**Comment by BruceCherniak** [comment]
You have the specular set to 0.0.  Set the specular value to 1.0 and you should get the look you're going for. 

With OSPRay's Principled material, `specular` and `metallic` work together
```C
    const float conductor = metallic * specular;
``` 
https://github.com/ospray/ospray/blob/5269850081d1c7d6da59b3c4f3cbac5c732374ba/ospray/render/materials/Principled.ispc#L319

**Comment by howetuft** [comment]
Hello,
Thank you for your quick answer! Quite unusual for me, but I'll try to cope with it.

**Comment by BruceCherniak** [comment]
If I might ask, quite unusual in what way?  If you'd prefer, when you have a material with `metallic > 0.f`, just don't specify the `specular` and OSPRay will default to 1.f.

All of the default values for OSPRay's materials are listed here https://www.ospray.org/documentation.html#materials

**Comment by howetuft** [comment]
In all the renderers I know, the `metallic` parameter of the Principled shader is _independent_ of the `specular` parameter.
To illustrate, here is the same scene as above, with `metallic=1` and `specular=0`, rendered with several other renderers (source files attached below pictures):

Appleseed:
![appleseed_cube](https://user-images.githubusercontent.com/34142192/136091059-776a909d-74a2-47d0-8374-2aaeba07a6ea.png)
([appleseed.zip](https://github.com/ospray/ospray_studio/files/7288747/appleseed.zip))

Cycles:
![cycles_cube](https://user-images.githubusercontent.com/34142192/136091192-33d086e3-a2c7-4e39-a770-d45b8cef2975.png)
([cycles.zip](https://github.com/ospray/ospray_studio/files/7288754/cycles.zip))

Luxcore:
![luxcore_cube](https://user-images.githubusercontent.com/34142192/136093196-fcc7b8c3-6df0-4341-a3e6-89843cb42022.png)
([luxcore.zip](https://github.com/ospray/ospray_studio/files/7288844/luxcore.zip))

.

I was expecting the same behavior from Ospray, that's why I said "unusual". Anyway, the tip you proposed should do the job, thanks!

**Comment by BruceCherniak** [comment]
Thanks for pointing out the difference in our material implementation.  We're considering a change to conform.  We'll let you know if/when things change.

**Comment by howetuft** [comment]
[Reopening]

I modified my [Project](https://github.com/ospray/ospray_studio/files/7317939/Project.zip) to comply with the above requirements (`metallic 1` and `specular 1`).
The rendering is better, but there is still a problem: some faces remain black:
![studio 0001](https://user-images.githubusercontent.com/34142192/136707823-6cb58a0b-a88d-45f8-b895-8b255938953a.png)

I suspect a problem with the normals (especially since, when I invert them in Transform menu, the black faces and the rendered faces are switched).
However, inspection of the OBJ normals in Blender does not reveal anything wrong:
![blender](https://user-images.githubusercontent.com/34142192/136707882-e3d2cedf-fb62-47bf-b848-11ae82448919.png)

 Could someone help me please? Many thanks in advance!

**Comment by BruceCherniak** [comment]
I'm not quite sure what's going on, but it is not unique to OSPRay.  If I import your 3 objects into Blender and render with Cycles, I see the same thing.  Orienting just right you can see the blackness sweeping over the top face -- interestingly it's not along the triangulated diagonal either.  One of the side faces has this same error.

The default cube (using quads, in the foreground) does not show this error.

![github5](https://user-images.githubusercontent.com/10440020/136710171-f043be19-e903-45fe-9efe-e2cbbbda3ab6.png)

**Comment by howetuft** [comment]
Thank you for your responsive answer! I hadn't thought of rendering the whole scene in Blender, I'll look into it

**Comment by howetuft** [comment]
You were right, there is a problem in the OBJ file (with the normals). It's about the exporter, not OSPRay. So, I close this issue, thanks again for your answer!
