### ISSUE TITLE
Segmentation fault with sunSky light

### ISSUE THREAD

**Issue by howetuft** [ospray/ospray_studio#6]
This [Project](https://github.com/ospray/ospray_studio/files/7357300/Project.zip) generates a segmentation fault.
I suspect this is related to the lack of a `renderer` node in the .sg file in conjunction with the use of a `sunSky` light (see this [code line](https://github.com/howetuft/ospray_studio/blob/master/sg/scene/lights/LightsManager.cpp#L41)).
However, this raises two questions:

- Is the `renderer` node mandatory in the .sg file (and, if so, where is this documented)?
- Shouldn't we expect a more user-friendly message?
 
Many thanks in advance for your answers!

**Comment by howetuft** [comment]
Note: the above project used to run flawlessly with v0.6.0.

**Comment by BruceCherniak** [comment]
Thanks for the issue. I'll take a look.

The .sg file is a direct json representation of internal SceneGraph state, we can't yet guarantee compatibility between Studio release versions.  However, a crash is definitely not a good thing.

.sg loading and compatibility is high on our todo list.

**Comment by BruceCherniak** [comment]
I took a look at this .sg file.  It's considerably different than current v0.8.0 scene graph format.  Until we reach a better level of stability with internal scene-graph format, unfortunately these are going to change somewhat.

This will make it difficult to hand-write .sg files.  The simplest thing to do is to save a .sg from the new version.  If you have a file with a lot of customization it's fairly easy to copy/paste from the old to the new.

If you don't mind, let's please close this as "change in file format incompatibility".  Meanwhile we will work on better documentation.  The `renderer` is best documented in the code.

**Comment by BruceCherniak** [comment]
In general, OSPRay Studio mimics the OSPRay API concepts.  

The documentation there is quite good:
https://www.ospray.org/documentation.html
https://www.ospray.org/documentation.html#renderers

**Comment by howetuft** [comment]
Thank you for your answer. Well, I'm a bit reluctant to close this issue at this stage, for two reasons:
1. I would like to have a chance to convert my test file into the new format, and thus verify that it is indeed a format problem in my file, and not something else affecting the program. Unfortunately, this will take me a few days, as I'm a bit overwhelmed.
2. At any rate, the program should not crash if a bad input format is applied. This should be fixed to close this issue, IMHO.

**Comment by BruceCherniak** [comment]
Good and valid points.  Thanks.  I'll try to create a quick/easy update to your Project.sg file.  And you're correct, crashing is unacceptable.  I'm working on versioning the .sg files so that older can be protected from major changes.  In the beta stages it's still very in flux.

**Comment by howetuft** [comment]
Hi,

Finally, it's confirmed that it's the format of my file that's at fault. I was able to regenerate a reformatted project
([ProjectReformatted.zip](https://github.com/ospray/ospray_studio/files/7403405/ProjectReformatted.zip)) that works fine: the fix is to insert the `sunSky` light into a `lightsManager` node, being a direct child of `frame`, and not into the `world` node as previously in version 0.6.0 (perhaps the [OSPRay Studio SG Structure]( https://www.ospray.org/ospray_studio/api.html#ospray-studio-sg-structure) documentation section should be updated?).

This solves point 1 above! There is still point 2, but I'll let you see if you want to keep the issue open or not...

Anyway, thanks a lot for your help!

**Comment by BruceCherniak** [comment]
Great, thank you for taking the time to confirm that and to point out the out of date documentation (oops, sorry).

I will keep this issue open to track both:
- Documentation needs to be updated
- Application must not crash when loading a scene-file with older format.

I really appreciate your support.  I'm excited to see some of your progress in `FreeCAD-render` when you are ready.

**Comment by BruceCherniak** [comment]
Both documentation and code have been updated in the v0.9.0 release found here https://github.com/ospray/ospray_studio/releases/tag/v0.9.0.  When you get a chance, please verify and close this issue.

**Comment by howetuft** [comment]
Thank you! Documentation is fine, however I still get a Segmentation Fault when I apply v0.9.0 to my initial file [Project.zip](https://github.com/ospray/ospray_studio/files/7531842/Project.zip). Is that correct?

**Comment by BruceCherniak** [comment]
No, we should never segfault.  I must have modified my version of your project slightly and didn't realize it when testing this fix.  I have a simple patch that I'll push to the github devel branch shortly.

Mind you, it doesn't crash, but it also might not display exactly as you intended, since the .sg file was created with an earlier version of Studio.  However, if you modify it once loaded and resave, it should be exactly as you intended.

Thanks for you patience.

**Comment by BruceCherniak** [comment]
The github devel source branch now contains a fix for this.   There are no binaries yet available, but if you build your own it should be resolved.

**Comment by howetuft** [comment]
Hello,
Sorry for the delay. I was finally able to test the devel version and it solves the bug perfectly, thanks! I close the issue.
