### ISSUE TITLE
glTF texture coordinates flipped after adding an HDRI light source

### ISSUE THREAD

**Issue by emackey** [ospray/ospray_studio#7]
Steps to reproduce:

1. Launch OSPRay Studio (I'm using 0.8.1 on Win64).
2. Go to Edit -> Lights...
3. Set "type" to "hdri", enter a name, and select an HDRI file.  I'm using the [Aerodynamics Workshop](https://polyhaven.com/a/aerodynamics_workshop) at 2k resolution.
4. Click "Add" and the HDRI should become visible as a background.
5. Close the "Lights" dialog.
6. Go to File -> Import... and choose a glTF model with text, such as [TextureSettingsTest](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TextureSettingsTest).

The texture coordinates come out flipped, like this:

![screenshot with flipped text](https://user-images.githubusercontent.com/1235080/139922785-ef1f6afb-4357-41f7-b3fb-859947fcfebc.png)

**Comment by BruceCherniak** [comment]
Thanks for the report, Ed.  Ooops, weird.  I'll look at this one today.

**Comment by BruceCherniak** [comment]
Just checked and was able to reproduce your error.  Odd that it doesn't happen if you load the model first and then the HDRI.  It's not unique to Windows. It is the fallback, non-OpenImageIO, texture loading path.  I'll fix it asap.  

(Once this does work, please note, it is understood that we won't pass all of the texture wrap/clamp mode conformance tests just yet.  The sampler was written with simplicity and scientific visualization as primary goal.  These will be added over time.)

**Comment by BruceCherniak** [comment]
OK, I've got a fix for this and it will make it into our v0.9.0 release toward the end of this week.  TIL that STBi  `stbi_set_flip_vertically_on_load` is static state.

**Comment by BruceCherniak** [comment]
This is in the v0.9.0 release round here https://github.com/ospray/ospray_studio/releases/tag/v0.9.0.  If you can, please verify and close this issue.  Thanks.
